version: '3'

services:

  vtiger:
    image: javanile/vtiger-dev:7.1.0
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=vtiger
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - ./languages:/var/lib/vtiger/languages:rw
      - vtiger:/var/lib/vtiger:rw
    ports:
      - 8080:80
    links:
      - mysql

  mysql:
    image: mysql:5.5
    environment:
      - MYSQL_DATABASE=vtiger
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql:/var/lib/mysql:rw

volumes:
  mysql:
  vtiger:
